# Generated by Django 2.2.8 on 2020-03-14 20:54

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200, verbose_name='Nombre')),
                ('password', models.TextField(verbose_name='Password')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo')),
                ('contacto', models.CharField(max_length=200, verbose_name='Nombre')),
                ('admin', models.BooleanField(default=False, verbose_name='Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.PositiveIntegerField(verbose_name='puntuacion')),
                ('descripcion', models.TextField(verbose_name='descripcion')),
                ('linksGameplay', models.TextField(verbose_name='links')),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('votantes', models.TextField(verbose_name='votantes')),
                ('created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='criticaJuegos.Usuario')),
            ],
        ),
    ]
