# Generated by Django 2.2.8 on 2020-03-15 13:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='photos/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contacto',
            field=models.CharField(max_length=200, verbose_name='contacto'),
        ),
    ]
