# Generated by Django 3.0.4 on 2020-03-15 17:32

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0002_auto_20200315_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='worthgames/media/photos/'), upload_to=''),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticaJuegos.Juego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticaJuegos.Usuario')),
            ],
        ),
    ]
