# Generated by Django 2.2.8 on 2020-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0004_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='title',
            field=models.CharField(default='world of warcraft', max_length=200, verbose_name='title'),
            preserve_default=False,
        ),
    ]
