# Generated by Django 2.2.8 on 2020-03-16 20:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0005_juego_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='worthgames/static/images/'), upload_to=''),
        ),
    ]
