# Generated by Django 3.0.4 on 2020-03-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0007_auto_20200321_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='aceptado',
            field=models.BooleanField(default=False),
        ),
    ]
