# Generated by Django 3.0.4 on 2020-03-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticaJuegos', '0008_juego_aceptado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='puntuacion',
            field=models.FloatField(verbose_name='puntuacion'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='votantes',
            field=models.TextField(null=True, verbose_name='votantes'),
        ),
    ]
